# 开发环境配置

spring:
  devtools:
    restart:
      enabled: true
  thymeleaf:
    cache: false
  boot:
    admin:
      client:
        url: http://127.0.0.1:7001
  data:
    mongodb:
      uri: mongodb://127.0.0.1:27017/cli-user


# 日志配置
logging:
  config: classpath:config/log4j2-dev.xml